<a href="https://colab.research.google.com/github/Seedplant/React-Test/blob/master/%EC%B2%AB%EC%A7%B8%EB%82%A0_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**정종학 첫째날 작성코드**

In [1]:
print("hello world")

hello world


In [0]:
import tensorflow as tf

In [20]:
###리니어 리그레이션 모델###

# 데이터 준비
x = [
    [25.0, 1.0],
    [28.0, 0.0],
    [23.0, 1.0]
]

y = [
    [101.0],
    [100.0],
    [88.0]
]
# 모델을 작성
X = tf.placeholder(tf.float32, shape=(None, 2))
Y = tf.placeholder(tf.float32, shape=(None, 1))

W = tf.Variable(tf.random_normal([2, 1]))
B = tf.Variable(tf.random_normal([1]))

# H = X * W + B
H = tf.add(tf.matmul(X, W), B)

# "오차" 계산
# cost = (H - Y)^2

cost = tf.square(tf.subtract(H, Y))
cost = tf.reduce_mean(cost)
optimizer = tf.train.AdamOptimizer(1).minimize(cost)

# 학습 & 평가

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(1000):
    sess.run(optimizer, feed_dict={X: x, Y: y})
    if i % 100 == 0:
      print(sess.run(cost, feed_dict={X: x,  Y: y}))
      



13974.534
7.13682
6.6284966
6.5617065
6.484552
6.3958526
6.2965684
6.187471
6.069121
5.942163


In [25]:
print(sess.run([W, B]))

[array([[3.5524116],
       [8.480064 ]], dtype=float32), array([0.75263524], dtype=float32)]


In [0]:
# 판매예측 = 3.55 *온도 + 8.48*휴일 - 7.25

tf.Session / run

In [28]:
# 모델을 만들고
x = tf.constant('hellow, tensorflow world')

# 모델을 실행합니다.
sess = tf.Session()
sess.run(x)


b'hellow, tensorflow world'

In [42]:
# 모델을 만들고
tf.reset_default_graph()   #그래프 초기화

x = tf.constant(10.0)
w = tf.constant(3.0)
b = tf.constant(5.0)

# h = x * w +b
h = tf.add(tf.multiply(x, w), b)
              

# 모델을 실행합니다.
sess = tf.Session()
print(sess.run(h))
print(sess.run([h, x, w, b]))

35.0
[35.0, 10.0, 3.0, 5.0]


In [76]:
# 모델을 만들고
x = tf.constant(100.0)
w = tf.Variable(10.0)

#  cost = (x - w)^2
cost = tf.square(tf.subtract(x, w))
optimizer = tf.train.AdamOptimizer(1).minimize(cost)


<tf.Variable 'Variable_4:0' shape=() dtype=float32_ref>


In [0]:
# 모델을 실행합니다.
sess = tf.Session()
sess.run(tf.global_variables_initializer())


# i값이 0 부터 99 까지 반복해주셍
for i in range(300):
    sess.run(optimizer)
    # i값이 10으로 나누어 떨어질 때에만 출력해주세요.
    if i % 30 == 0:
        print(sess.run(w))


tf.Variable / tf.global_variables_initializer / optimizer

In [59]:
# 모델을 만들고
x = tf.constant(100.0)
w = tf.Variable(10.0)

#  cost = (x - w)^2
cost = tf.square(tf.subtract(x, w))
optimizer = tf.train.AdamOptimizer(1).minimize(cost)


# 모델을 실행합니다.
sess = tf.Session()
sess.run(tf.global_variables_initializer())


# i값이 0 부터 99 까지 반복해주셍
for i in range(300):
    sess.run(optimizer)
    # i값이 10으로 나누어 떨어질 때에만 출력해주세요.
    if i % 30 == 0:
        print(sess.run(w))





11.0
39.92083
63.798588
80.73137
91.09843
96.500565
98.86045
99.70756
99.947784
99.99656


## tf.placeholder / feed_dict

In [73]:
# 데이터를 준비한다
x = 100.0


# 모델을 만들고
tf.reset_default_graph()

X = tf.placeholder(tf.float32, shape=())    # placeholder 변수를 넣어주는 입구 shape 형태로
W = tf.Variable(10.0)                         #변하는 변수, 10.0을 찾아가는 변수

cost = tf.square(tf.subtract(x, W))
optimizer = tf.train.AdamOptimizer(1).minimize(cost)


#모델을 실행한다.
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(100):
      sess.run(optimizer, feed_dict={X:x})
      if i % 10 == 0 :
          print(sess.run([W, cost], feed_dict={X:x}))


[11.0, 7921.0]
[20.948132, 6249.1973]
[30.65346, 4808.943]
[39.92083, 3609.5066]
[48.597115, 2642.2566]
[56.57741, 1885.5211]
[63.798588, 1310.5422]
[70.2304, 886.22906]
[75.86878, 582.3157]
[80.73137, 371.28015]


In [0]:
# 데이터를 준비한다
x = 100.0


# 모델을 만들고
tf.reset_default_graph()

X = tf.placeholder(tf.float32, shape=())    # placeholder 변수를 넣어주는 입구 shape 형태로
W = tf.Variable(10.0)                         #변하는 변수, 10.0을 찾아가는 변수

cost = tf.square(tf.subtract(x, W))
optimizer = tf.train.AdamOptimizer(1).minimize(cost)



In [80]:
#모델을 실행한다.
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(100):
      sess.run(optimizer, feed_dict={X:x})
      if i % 10 == 0 :
          print(sess.run([W, cost], feed_dict={X:x}))


[11.0, 7921.0]
[20.948132, 6249.1973]
[30.65346, 4808.943]
[39.92083, 3609.5066]
[48.597115, 2642.2566]
[56.57741, 1885.5211]
[63.798588, 1310.5422]
[70.2304, 886.22906]
[75.86878, 582.3157]
[80.73137, 371.28015]


shape & matrix

In [0]:
a = [1, 2, 3, 4]
b = [[1, 2],
     [3, 4],
     [5, 6]]
    

In [0]:
sess = tf.Session()

In [86]:
A = tf.constant(a)
print(sess.run(tf.shape(A)))

[4]


In [87]:
B = tf.constant(b)
print(sess.run(tf.shape(B)))


[3 2]


In [88]:
C = tf.constant(3)
print(sess.run(tf.shape(C)))

[]


In [95]:
A = tf.constant([1, 2, 3, 4])
B = tf.constant(3)

C = tf.add(A, B)
print(sess.run(C))

[4 5 6 7]


In [92]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = 3

print(a*b)

[ 3  6  9 12]


In [94]:
import numpy as np

a = np.array([
    [1,2],
    [3,4],
    [5,6]
])

b = 3

print (a*b)

[[ 3  6]
 [ 9 12]
 [15 18]]


linear regression

In [104]:
# 데이터를 준비한다. Linear regression : 여러 점들을 가장 잘 설명할 수 있는 선분을 찾는것 -> f(x)
x = [
    [20.0, 1.0],
    [25.0, 0.0],
    [23.0, 1.0]
]

y = [
    [100.0],
    [90.0],
    [120.0]
]

##############################
#모델을 작성한다.
import tensorflow as tf
tf.reset_default_graph()


# 데이터를 받을 곳
X = tf.placeholder(tf.float32, shape = (3,2))          # float 뒤 숫자를 16, 8 등으로 줄이면  GPU 메모리의 과부하를 감소시킬수 있다.
Y = tf.placeholder(tf.float32, shape = (3,1))          # shape=(None, 1) 이면 입력되는 데이터 매트릭스가 변하는 경우에 처리가능하다

# 머신이 할습할 데이터
#W = tf.Variable([[1.0],      => 초기 값을 지정해주는 경우
#                 [1.0]])
#B = tf.Variable ([1.0])
W = tf.Variable(tf.random_normal([2,1]))    # 초기값을 랜덤하게 지정해주는 경우지만 그래도 정규분포 기준으로 주어진다라는~~?
B = tf.Variable(tf.random_normal([1]))



# H = X * W + B
H = tf.add(tf.matmul(X, W), B)

# 오차 optimizer
# cost = (Y - H)^2
cost = tf.square(tf.subtract(Y, H))
cost = tf.reduce_mean(cost)
optimizer = tf.train.AdamOptimizer(0.01).minimize(cost)


###############################shape()는 매트릭스 형태를 뜻함.
# 모델을 학습시킨다.
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(1000):
      sess.run(optimizer, feed_dict={X:x, Y:y})
      if i % 100 == 0 :
          print(sess.run(cost, feed_dict={X:x, Y:y}))

14302.427
9278.477
5745.338
3394.6758
1922.8519
1062.8484
597.3653
365.18295
258.53232
212.98067


In [103]:
sess.run([W, B])

[array([[4.1618586],
        [6.0430717]], dtype=float32), array([4.34507], dtype=float32)]

In [0]:
x = [
    [20.0, 1.0],
    [25.0, 0.0],
    [23.0, 1.0]
]

y = [
    [100.0],
    [90.0],
    [120.0]
]

H = 4.16*2~